### PR TITLE
Government Portals and Interest Groups case studies

### PR DESCRIPTION
**Pull request by betsybookwyrm**

### CODE REVIEW

**Comment by betsybookwyrm** [comment]
Still working on the illustration for the Government Portals one. 

I also feel like I should go back and improve the IG one now that I got something I'm much happer with together for government portals, but we'll seee....

**Comment by betsybookwyrm** [comment]
ok, full drafts are up!

@Lingomat can you look at the Government Portals one and edit it or let me know anything I've missed or should change?
@deimosnz same for Interest Groups please?

@boyd-nguyen I need your help making the illustration in the government portals one sit nicely, it's sticking out the right-hand side and if you've got a fancy bootstrap class that will make it nicer that would be better

**Review by Quiet27 — APPROVED** [review]
Awesome! Thanks @betsybookwyrm 

I made some minor changes to the text, and adjusted the positioning of the images to be limited to 100% of the page width to avoid having a horizontal scroll bar.

🚀

**Comment by betsybookwyrm** [comment]
> Awesome! Thanks @betsybookwyrm
> 
> I made some minor changes to the text, and adjusted the positioning of the images to be limited to 100% of the page width to avoid having a horizontal scroll bar.
> 
> 🚀

Thank you Alice!!

**Comment by betsybookwyrm** [comment]
Merging as discussed in dev meeting/ team meeting. We can always edit more later :)

**Pull request merged**
