### PR TITLE
add favicon

### PR DESCRIPTION
**Pull request by boyd-nguyen**
- added a favicon icon so that ADO logo shows up in browser tabs

### CODE REVIEW

**Review by betsybookwyrm — APPROVED** [review]
On the icon itself - I probably wouldn't change the aspect ratio quite so much, it seems really squished and I'd rather only squish it a little and have a bit of empty space top and bottom (or maybe just do the O?). But really not a big deal, it's fine as it is.

**Review by Quiet27 — COMMENTED** [review]
Great idea!

It shows up a little squished for me. Also, it might be better to use an icon with a white background. This is how it shows up in Google Chrome on Windows (using a dark theme) when the tab is inactive:
image

and this is how it looks when the tab is active:
image

**Comment by boyd-nguyen** [comment]
@betsybookwyrm @Quiet27 Yeah the ADO logo is not exactly square to be used as a favicon. I'll try using just the O as Betsy suggested

**Review by Quiet27 — APPROVED** [review]
Love it! Thanks Boyd 🚀

**Comment by betsybookwyrm** [comment]
The new icon looks great :)

**Pull request merged**
