### PR TITLE
Refresh/update of publications

### PR DESCRIPTION
**Pull request by Quiet27**

### CODE REVIEW

**Comment by Quiet27** [comment]
Remaining publications to add:

- [ ] Graham, T., Bruns, A., Angus, D., Hurcombe, E., & Hames, S. (2021). #IStandWithDan versus #DictatorDan: The polarised dynamics of twitter discussions about victoria’s COVID-19 restrictions. Media International Australia, 179(1), 127–148. Retrieved from https://doi.org/10.1177/1329878X20981780
- [ ] Keller, T., Graham, T., Angus, D., & Bruns, A. (2020). #ARSONEMERGENCY: Climate change disinformation during the australian bushfire season 2019-2020. Selected papers in internet research 2020 : Research from the 21st annual conference of the association of internet researchers, AoIR selected papers of internet research. United States of America: Association of Internet Researchers (AoIR). Retrieved from https://eprints.qut.edu.au/209942/
- [ ] Layt, S. (2020, June). How social media was ahead of the curve when it came to COVID-19. The Age. Retrieved January 11, 2021, from https://www.theage.com.au/national/queensland/how-social-media-was-ahead-of-the-curve-when-it-came-to-covid-19-20200629-p557cp.html
- [ ] Monteiro Lunardi, G. (2022). The ’Brazilian-ness’ of Brazilian YouTube: New voices, new platforms, new television? (phd). Queensland University of Technology. Retrieved August 23, 2022, from https://eprints.qut.edu.au/233173/
- [ ] Queensland University of Technology. (2019, May). Election Twitter chatter: Who’s sharing and what’s trending. QUT News. Retrieved January 11, 2021, from https://www.qut.edu.au/news?id=144270
- [ ] Queensland University of Technology. (2020b, November). Social media can guide public pandemic policy: QUT research. QUT News. Retrieved January 11, 2021, from https://www.qut.edu.au/news?id=170713
- [ ] Queensland University of Technology. (2020a, June). First 100 days of COVID-19 - Australian Twitter users’ concerns mapped. QUT News. Retrieved January 11, 2021, from https://www.qut.edu.au/news?id=164908
- [ ] Vasconcelos Silva, C., Jayasinghe, D., & Janda, M. (2020). What Can Twitter Tell Us about Skin Cancer Communication and Prevention on Social Media? Dermatology, 236(2), 81–89.

**Comment by Quiet27** [comment]
Link to the corresponding issue for this PR: https://github.com/QUT-Digital-Observatory/australian_digital_observatory_site/issues/46

**Review by boyd-nguyen — COMMENTED** [review]
@Quiet27 I made one very tiny edit. If you're happy with it I'll approve and merge this branch

**Comment by Quiet27** [comment]
> @Quiet27 I made one very tiny edit. If you're happy with it I'll approve and merge this branch

Perfect! Feel free to approve and merge 😺

**Review by boyd-nguyen — APPROVED** [review]

**Pull request merged**
