### PR TITLE
update links in SEE MORE button + open external links on new tab

### PR DESCRIPTION
**Pull request by boyd-nguyen**
- Some of the publication links are broken or accessed through QUT library, so I replaced them with the public links.
- Added a new publication from Autism project
- Made links clickable in the resources' metadata table
- External links were made to open in a new tab

### CODE REVIEW

**Comment by boyd-nguyen** [comment]
A lot of UniMelb resources are either out of date or really vague. I don't know what to do with them

**Comment by betsybookwyrm** [comment]
> A lot of UniMelb resources are either out of date or really vague. I don't know what to do with them

Yeah, it's a bit tricky.

A lot of the single-platform listings e.g. Flickr that are included in ADOReD (according to https://www.ado.eresearch.unimelb.edu.au/data-and-methods/) we could probably remove the individual listings and perhaps copy a list of data sources from their website and add it to the ADOReD blurb.

It might be a good idea to send the UniMelb team a list of the pages for their resource and ask that they either update them or send us instructions (delete, merge, update with provided details) for them so we can wrap up the ADO time with up-to-date info. @mctakahashi , what do you think?

**Review by Quiet27 — APPROVED** [review]
Thanks Boyd! I added my recent publication as well (thought I may as well get it in with this branch).

**Comment by boyd-nguyen** [comment]
Thanks Alice and Betsy!

**Pull request merged**
