### PR TITLE
Draft for Australian Twittersphere Eulogy blog

### PR DESCRIPTION
**Pull request by boyd-nguyen**

### CODE REVIEW

**Comment by Quiet27** [comment]
@boyd-nguyen I think I have added all that I can. There's just one piece left at the end: an update on the status of APIs. After that, I think it's good to go!

**Comment by boyd-nguyen** [comment]
@Quiet27 Thank you so much! The edits are massively helpful! I'll write up the rest

**Comment by Quiet27** [comment]
@boyd-nguyen no worries, thanks for getting it started in the first place. One other thing I just remembered: the publication list is a bit big, so we might want to move it to the bottom, but refer to it where we mention the disciplines. Interested people can continue scrolling down to read through all the other publications, but others don't have to, and at least they won't have missed the "What's next for DO" heading if they already moved on.

**Comment by boyd-nguyen** [comment]
@Quiet27 I've done one more round of edits. Could you have another look and suggest changes or approve, please?

**Comment by Quiet27** [comment]
@boyd-nguyen I've made some more changes to keep the wording a little more positive - see what you think?

**Comment by boyd-nguyen** [comment]
@Quiet27 They sound great! I have no more changes to make. Thank you

**Review by Quiet27 — APPROVED** [review]

**Pull request merged**
